Repository fluxcd/image-automation-controller, pull requests merged in 2021-11, with the labels that each got.

#259 Add the commit message to the event body
  controllers/imageupdateautomation_controller.go
Labels: enhancement

#262 Replace strings.TrimRight with strings.TrimSuffix
  pkg/update/setters.go
Labels: bug

#263 Fix LIBGIT2_VERSION variable used in Makefile
  Makefile
Labels: area/build

#264 Fix LIBGIT2_VERSION variable used in Makefile [cherry-pick]
  Makefile
Labels: area/build

#267 Remove deprecated `io/ioutil`
  controllers/git_test.go
  controllers/imageupdateautomation_controller.go
  controllers/update_test.go
  pkg/test/files.go
  pkg/update/filereader.go
  pkg/update/update_test.go
Labels: area/build

#268 Update controller-runtime to v0.10.2
  Makefile
  api/go.mod
  api/go.sum
  controllers/update_test.go
  go.mod
  go.sum
Labels: area/build

#269 Update image-reflector-controller and source-controller
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build
