Repository fluxcd/image-automation-controller, pull requests merged in 2021-03, with the labels that each got.

#124 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#125 Explain how the push field works
  docs/spec/v1alpha1/imageupdateautomations.md
Labels: documentation

#126 Allow specifying the path for manifests updates
  api/v1alpha1/imageupdateautomation_types.go
  config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml
  controllers/imageupdateautomation_controller.go
  controllers/suite_test.go
  controllers/testdata/pathconfig/no/deploy.yaml
  controllers/testdata/pathconfig/yes/deploy.yaml
  controllers/update_test.go
  docs/api/image-automation.md
  docs/spec/v1alpha1/imageupdateautomations.md
  go.mod
  go.sum
Labels: enhancement

#127 Add CodeQL scanning to CI
  .github/workflows/fossa.yml
  .github/workflows/scan.yml
  Makefile
  go.mod
  go.sum
Labels: area/build

#130 Fix typo in template code example
  CHANGELOG.md
  docs/spec/v1alpha1/imageupdateautomations.md
Labels: documentation

#137 Set leader election deadline to 30s
  go.mod
  go.sum
  main.go
Labels: enhancement

#141 Update kyaml to v0.10.16
  Makefile
  go.mod
  go.sum
Labels: area/build
