Repository fluxcd/image-automation-controller, pull requests merged in 2022-01, with the labels that each got.

#248 Update Go to v1.17
  .github/actions/run-tests/Dockerfile
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml
  controllers/imageupdateautomation_controller.go
  go.mod
  go.sum
  pkg/update/filereader.go
  pkg/update/filereader_test.go
  pkg/update/filter.go
Labels: area/build

#292 Fix makefile envtest and controller-gen usage
  .github/workflows/build.yaml
  .gitignore
  Makefile
  controllers/suite_test.go
Labels: area/build

#295 Drop capabilities, enable seccomp and enforce runAsNonRoot
  Dockerfile
  config/manager/deployment.yaml
Labels: area/build

#301 Update dev docs
  DEVELOPMENT.md
  Makefile
Labels: documentation

#299 Add support for cross-namespace sourceRef in ImageUpdateAutomation
  api/v1beta1/imageupdateautomation_types.go
  api/v1beta1/reference.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml
  controllers/imageupdateautomation_controller.go
  controllers/update_test.go
  docs/api/image-automation.md
Labels: enhancement

#302 Publish SBOM and sign release artifacts
  .github/workflows/build.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  .goreleaser.yaml
  config/manager/deployment.yaml
Labels: enhancement, area/build

#288 Update kyaml to v0.13.0
  controllers/testdata/appconfig-expected/deploy.yaml
  controllers/testdata/appconfig-expected2/deploy.yaml
  controllers/testdata/appconfig-setters-expected/deploy.yaml
  go.mod
  go.sum
  pkg/update/testdata/replace/expected/cronjob.yaml
  pkg/update/testdata/replace/expected/deployment.yaml
  pkg/update/testdata/setters/expected/kustomization.yaml
  pkg/update/testdata/setters/expected/marked.yaml
Labels: area/build

#304 Update source-controller packages to 0.21.0
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#305 Allow disabling cross-namespace references
  controllers/imageupdateautomation_controller.go
  controllers/update_test.go
  docs/spec/v1beta1/imageupdateautomations.md
  go.mod
  go.sum
  main.go
Labels: enhancement
