Repository fluxcd/image-automation-controller, pull requests merged in 2023-05, with the labels that each got.

#516 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#518 Update controller-runtime, Kubernetes and kyaml dependencies
  .gitignore
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml
  docs/spec/v1beta1/imageupdateautomations.md
  go.mod
  go.sum
  internal/controller/controllers_fuzzer_test.go
  internal/controller/imageupdateautomation_controller.go
  internal/controller/imageupdateautomation_controller_test.go
  internal/controller/suite_test.go
  internal/controller/testdata/appconfig-expected/deploy.yaml
  internal/controller/testdata/appconfig-expected2/deploy.yaml
  internal/controller/testdata/appconfig-setters-expected/deploy.yaml
  internal/controller/testdata/appconfig/deploy.yaml
  internal/controller/testdata/brokenlink/bar.yaml
  internal/controller/testdata/pathconfig/no/deploy.yaml
  internal/controller/testdata/pathconfig/yes/deploy.yaml
  internal/controller/update_test.go
  main.go
  tests/fuzz/oss_fuzz_prebuild.sh
Labels: dependencies

#519 Drop go-git fork in favor of go-git v5.7.0
  go.mod
  go.sum
  internal/controller/controllers_fuzzer_test.go
  internal/controller/imageupdateautomation_controller.go
  internal/controller/update_test.go
Labels: area/git, dependencies

#523 Update source-controller to v1.0.0-rc.4
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#527 Return signing entity parsing error
  internal/controller/imageupdateautomation_controller.go
Labels: bug
