Repository fluxcd/image-automation-controller, pull requests merged in 2023-07, with the labels that each got.

#553 Update go-git to unreleased v5.8.0
  go.mod
  go.sum
Labels: area/git, dependencies

#554 Update Go dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#555 Bump source-controller and image-reflector-controller APIs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#556 ci: various workflow changes
  .github/workflows/cifuzz.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: area/ci

#559 ci: various workflow changes
  .github/dependabot.yaml
  .github/workflows/backport.yaml
Labels: area/ci

#560 Fix GHA backport.yaml workflow job perms
  .github/workflows/backport.yaml
  .github/workflows/release.yml
Labels: area/ci
