Repository fluxcd/image-automation-controller, pull requests merged in 2023-08, with the labels that each got.

#568 ci: enable security-and-quality CodeQL query
  .github/workflows/scan.yml
Labels: area/ci

#571 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#573 Fix links in API docs
  docs/spec/v1beta1/imageupdateautomations.md
Labels: dependencies

#514 git: add push.refspec to push using a refspec
  api/v1beta1/git.go
  config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml
  docs/api/v1beta1/image-automation.md
  docs/spec/v1beta1/imageupdateautomations.md
  internal/controller/imageupdateautomation_controller.go
  internal/controller/update_test.go
Labels: enhancement, area/git

#565 add support for specified proxy in source GitRepository
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controller/imageupdateautomation_controller.go
  internal/controller/update_test.go
Labels: enhancement, area/git

#577 add support for specifying push options
  api/v1beta1/git.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml
  docs/api/v1beta1/image-automation.md
  docs/spec/v1beta1/imageupdateautomations.md
  internal/controller/imageupdateautomation_controller.go
Labels: enhancement, area/git, area/api
